# Generated by Django 3.2.9 on 2021-11-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frequency', models.CharField(choices=[('m', 'monthly'), ('d', 'daily'), ('w', 'weekly'), ('q', 'quarterly'), ('ba', 'bi-annual'), ('y', 'yearly')], default='m', max_length=2)),
            ],
            options={
                'verbose_name': 'Постоянный месячный расход',
                'verbose_name_plural': 'Постоянные месячные расходы',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='RegularMonthlyExpenses',
        ),
    ]
