# Generated by Django 3.2.9 on 2021-11-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_rename_envelopes_spaces'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spaces',
            new_name='Space',
        ),
    ]
